<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata Sandi_password</name>
   <tag></tag>
   <elementGuidId>8c8c3f4a-c45e-43db-9179-3b9e4f204378</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auth-input-container > input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='password'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e90b1ff5-882d-4887-8f14-74bb4aed5230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9303e81f-3b0f-495f-903b-3d84c30eb438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kata sandi Anda</value>
      <webElementGuid>285e4313-ba5d-4c7e-b386-5548444667f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>530599c4-0b2b-4b0e-af06-e3746dc0a153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c7b3a130-2c5f-467e-93ac-f2961c54592d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-input ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>2fb9a961-f120-498f-8da1-9dbeefda2f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8e4d959a-fc13-4813-9e2f-c9e30d38faf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/login-password-dialog[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;auth-dialog&quot;]/div[@class=&quot;login-password-dialog__password&quot;]/form[@class=&quot;ng-untouched ng-dirty ng-valid&quot;]/div[@class=&quot;auth-mb-10&quot;]/div[@class=&quot;auth-input-container&quot;]/input[@class=&quot;auth-input ng-untouched ng-dirty ng-valid&quot;]</value>
      <webElementGuid>8b614eb3-4722-4696-8529-cd968f12439f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='password'])[2]</value>
      <webElementGuid>5538c5d0-7de7-472a-9d56-d3df9157cb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/login-password-dialog/section/div[3]/form/div/div[2]/input</value>
      <webElementGuid>6258a1b5-c213-4bbf-8983-d5b48125b613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div[2]/input</value>
      <webElementGuid>33b94576-c25c-4620-8ded-6647c385fb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan kata sandi Anda' and @name = 'password' and @type = 'password']</value>
      <webElementGuid>7498b38d-298f-4574-b640-e00063bfa7dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
