<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email atau No. Handphone_email</name>
   <tag></tag>
   <elementGuidId>6f611e66-f6e5-4945-863e-678fe95bb294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd7370c7-3a63-4628-b9e8-440937786171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>e11f98d5-88df-47f8-8c54-7b1f7c2b9c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16f206af-6dd1-47ee-9ba5-a348a71026b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan email atau no. handphone Anda</value>
      <webElementGuid>fe0cd5ff-9e9d-4096-8d66-3fae997d8bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>83f98ba5-8bf7-40aa-9131-beb79465ff5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f7b72b93-cfa2-4ab0-9614-8ca7961e6ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c6fc2150-30f6-45eb-8c76-2c090e1cb13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/app-root[1]/main[@class=&quot;normalize-modal&quot;]/auth-login[1]/div[@class=&quot;auth auth--blue&quot;]/div[@class=&quot;auth-grid&quot;]/div[1]/div[@class=&quot;auth-form__box&quot;]/form[@class=&quot;auth-mb-20 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;auth-mb-40&quot;]/div[@class=&quot;auth-input-container&quot;]/input[@class=&quot;auth-input ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>e42c7886-fd81-43b2-a2f2-ada6bbda9c3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>55ac648d-97c4-4d55-a95b-7d681be36579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='main-body']/app-root/main/auth-login/div/div[2]/div/div/form/div/div[2]/input</value>
      <webElementGuid>45886006-0949-4232-96fe-ddd7762cd264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f4d3ccbd-7d3d-4cf9-bf3a-69055fcbd6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan email atau no. handphone Anda' and @name = 'email']</value>
      <webElementGuid>16e2ede7-011d-41ff-9ef6-dd78b1a0cad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
