<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Produk dari Stok</name>
   <tag></tag>
   <elementGuidId>2f99a535-3228-4eaa-adbc-cd91feaf9148</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_product_list_modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_product_list_modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62433bd4-f19b-41e7-b735-dadd039d1141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_product_list_modal</value>
      <webElementGuid>e4c1cb69-f1d2-4f90-8102-61301fa6a7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbd3baeb-8e59-4653-99a2-48b36e694d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paper-button blue-button</value>
      <webElementGuid>423c38e0-c3da-44f9-9c26-774d8ba5eb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah Produk dari Stok </value>
      <webElementGuid>5ddd94b5-8aec-48ef-80de-4589b43ba722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_product_list_modal&quot;)</value>
      <webElementGuid>f6b7ec6b-7e58-4436-9fe9-a91cf241e37a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_product_list_modal']</value>
      <webElementGuid>712d46ab-7cc7-4387-81d4-0ef0d57d9412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='digpayin-step4']/invoice-items-list/div/button[2]</value>
      <webElementGuid>67488502-bfc4-47d9-8f65-de9500fc5c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Baris'])[1]/following::button[1]</value>
      <webElementGuid>30fa02ea-fafe-41b9-b322-1e98bc75cc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga'])[1]/following::button[2]</value>
      <webElementGuid>789ddf86-04ba-44cf-b20f-94a18bb1bd9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/preceding::button[1]</value>
      <webElementGuid>060dacc5-22fa-4c4b-88e7-4bd5e9e164c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Diskon'])[1]/preceding::button[1]</value>
      <webElementGuid>3776d563-05ff-490f-aac7-188eec20df2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Produk dari Stok']/parent::*</value>
      <webElementGuid>e1edcbbb-93d1-4455-a411-4c52ce82d4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>72d1b6a7-a43f-45ac-9e8f-e0ac8a1edf61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_product_list_modal' and @type = 'button' and (text() = ' Tambah Produk dari Stok ' or . = ' Tambah Produk dari Stok ')]</value>
      <webElementGuid>97b2aa96-aa7f-4c62-b26a-06f9f0e55bdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
