<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No Data Selected</name>
   <tag></tag>
   <elementGuidId>1837ece8-909b-4552-a0e7-90725d3e97a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ng-select[name=&quot;paper-lazy-load-dropdown&quot;] > div.ng-select-container > div.ng-value-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='digpayin-step3']/button-partner/div/div[2]/paper-lazy-load-dropdown/form/ng-select/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>66732b8f-a72d-459d-a8db-fe8d4f7658e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-value-container</value>
      <webElementGuid>a281b70b-5e56-48c1-b208-63e3c65e11f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No Data Selected</value>
      <webElementGuid>bbf5674f-b3cd-489c-b698-a85eca7d042c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digpayin-step3&quot;)/button-partner[@class=&quot;ng-tns-c680-30 ng-star-inserted&quot;]/div[@class=&quot;form-group form-group-sm&quot;]/div[2]/paper-lazy-load-dropdown[1]/form[@class=&quot;ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/ng-select[@class=&quot;ng-select ng-select-single ng-select-searchable ng-select-clearable ng-select-typeahead ng-untouched ng-pristine ng-invalid ng-select-focused ng-select-opened ng-select-top&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]</value>
      <webElementGuid>1635ea45-ca0d-4fb8-9d6a-37f58c25b6bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='digpayin-step3']/button-partner/div/div[2]/paper-lazy-load-dropdown/form/ng-select/div/div</value>
      <webElementGuid>9930ef99-26e3-488d-9f5a-6c594ca929a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[3]</value>
      <webElementGuid>ee339da6-65c7-4284-88a2-288202007da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acong'])[1]/preceding::div[4]</value>
      <webElementGuid>f8e0ea5c-9f40-4360-8b7c-7d4581be89ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ng-select/div/div</value>
      <webElementGuid>0b814d28-b922-4f41-896a-5d2f36b71787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'No Data Selected' or . = 'No Data Selected')]</value>
      <webElementGuid>7bcf3e55-b1fc-4331-9b5b-367393bec015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
