<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Acong</name>
   <tag></tag>
   <elementGuidId>e7e53e0e-0652-4c3a-b7c5-4fa7684c20c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#abe04ca9361f-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='abe04ca9361f-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0253374-398a-45d1-b270-4600306370ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>a72f010d-2ca1-4aa8-8591-cdcb9dc5d646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>abb6d024-4cbc-41a4-937f-319a504e16cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abe04ca9361f-0</value>
      <webElementGuid>08b46ac0-5931-4b99-8ac2-b258ba70b598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acong</value>
      <webElementGuid>d9198406-72c1-4d1c-b9ce-82c170ba49f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abe04ca9361f-0&quot;)</value>
      <webElementGuid>ca098827-d50c-4390-8e20-9de6652eb360</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='abe04ca9361f-0']</value>
      <webElementGuid>47cc3b4a-ae26-4c5e-af3f-2968b27c817f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='abe04ca9361f']/div/div[2]/div</value>
      <webElementGuid>cb2067ec-3de5-4535-ad4d-5949feca11af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Data Selected'])[1]/following::div[5]</value>
      <webElementGuid>1a512559-41d9-48d1-b7f6-699aebab75eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[9]</value>
      <webElementGuid>4dd07eb8-962d-4c54-addf-26070d5e0b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genteng Merah Jaya'])[1]/preceding::div[1]</value>
      <webElementGuid>dfda5bf1-7605-4d31-b783-cea6007968ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>45ea4166-9493-45a6-a004-12b6a6a41987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'abe04ca9361f-0' and (text() = 'Acong' or . = 'Acong')]</value>
      <webElementGuid>ec92aec0-e199-4e92-bdc4-ccfbcf2b03f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
