<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_by_close-button ng-tns-c305-43</name>
   <tag></tag>
   <elementGuidId>0ee980f9-f0c3-4d82-8c97-de794182dca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.close-button.ng-tns-c305-43</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-1']/invoice-addproduct/section/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4854b503-6876-44a4-b2fd-4ba106d1b834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-button ng-tns-c305-43</value>
      <webElementGuid>854c72fd-08a1-46c8-8aeb-b6b6fc2d406d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)/invoice-addproduct[@class=&quot;ng-tns-c305-43 ng-star-inserted&quot;]/section[@class=&quot;modal-form-container ng-tns-c305-43&quot;]/img[@class=&quot;close-button ng-tns-c305-43&quot;]</value>
      <webElementGuid>7072d507-7f58-40a2-86a9-25b354920198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/invoice-addproduct/section/img</value>
      <webElementGuid>846ab23c-79cc-4d6b-a8fb-6c6d12a7273a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/img</value>
      <webElementGuid>32fbfbeb-c75e-4369-aee1-773a5166abee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
