<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Kuantitas_price</name>
   <tag></tag>
   <elementGuidId>7dabc96c-fe47-45fc-8a5b-cac2f2517bf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>aef0b674-e069-4ba1-98d2-f5fa2a36ae18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>ebc160d7-f953-4abb-b050-267a1b88ce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>f12080f6-b801-4455-9931-985aeedd403b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5676d2db-ae92-4653-b0d2-bdc39fd767e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>a50f141c-e29a-42a8-b185-a80d88e3c798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c59-41 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-valid</value>
      <webElementGuid>2583b2c2-0bc7-4bc5-9e3d-7ec57ede0933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Harga</value>
      <webElementGuid>48efc7f6-1ad9-4f19-b243-8d0ade5b1b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51cc4a6c-82cd-48c3-8d1f-5defda61efed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f4cd2f5b-c417-478c-ba95-12ae81ea848b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;price&quot;)</value>
      <webElementGuid>b728448c-5e67-4d68-83a9-937cc38b1861</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='price']</value>
      <webElementGuid>6bb1956f-62f9-4a38-bd85-944599b6b0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='drag']/tr/td[5]/mat-form-field/div/div/div/textarea</value>
      <webElementGuid>9cd42d69-ce2b-4d9c-b6cf-3784a752ac66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/mat-form-field/div/div/div/textarea</value>
      <webElementGuid>151a6e81-a144-4cdb-9580-e65eda50f0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'price' and @name = 'price']</value>
      <webElementGuid>7c7fb9b6-f22e-402d-a4ee-99174115f65f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
