<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tahan klik untuk geser_item_name</name>
   <tag></tag>
   <elementGuidId>7bd52e14-6060-4b20-bf8b-a92d14730dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='item_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cf28bd32-7578-43c9-8240-fb18f590dc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_name</value>
      <webElementGuid>eed11cb8-e9a8-446b-992a-ddb2c70adceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_name</value>
      <webElementGuid>7af4c328-2572-4222-8e81-b657836f8112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b15b8158-9581-435a-8afd-6f72eceab3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c59-38 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-valid</value>
      <webElementGuid>4801c7af-0014-456c-8f93-a418847ea7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Nama Produk</value>
      <webElementGuid>0a906f09-c581-4279-b3fb-8e67005fb568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f65d1cc-c870-4414-94e3-a14ecaccbb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d77750b5-97ff-47ab-92c8-9db8f93b9f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_name&quot;)</value>
      <webElementGuid>d4f1ca7e-6e3f-4dc6-b619-795c5c554bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='item_name']</value>
      <webElementGuid>bd5abb21-66b8-4215-802a-b94feef9c561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='drag']/tr/td[2]/div/mat-form-field/div/div/div/textarea</value>
      <webElementGuid>4ec7b07c-e0f6-4109-9d4b-42d35f16b811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3d1e550f-72db-46f5-8ed1-e8359010f41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'item_name' and @name = 'item_name' and @type = 'text']</value>
      <webElementGuid>590e6eb4-684d-4c76-abf0-eeb928bf0430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
