<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Nama Produk_item_description</name>
   <tag></tag>
   <elementGuidId>cb36f481-0a64-49f5-a246-d407a2f68335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item_description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='item_description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9f699b40-69e2-48a8-a910-07b713d46bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_description</value>
      <webElementGuid>72304e60-5d58-4c2e-bc25-94022d78a002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_description</value>
      <webElementGuid>274104d6-da0f-4093-95d4-041ec5482527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c59-39 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-valid</value>
      <webElementGuid>93f56f2d-9e61-4fa9-a760-3c908c4419c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Deskripsi Produk</value>
      <webElementGuid>93a0bdc5-b66c-430b-86ca-7149e7d7a422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b7e8e43b-afde-4e5a-b381-61c9a4fad070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26ef52ba-ea6d-42ac-bd68-c8208870bf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_description&quot;)</value>
      <webElementGuid>f3caee2e-7fe1-4d72-a2b9-56f18575d32a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='item_description']</value>
      <webElementGuid>e227fb63-a1c0-4491-908a-63da52e5653a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='drag']/tr/td[3]/mat-form-field/div/div/div/textarea</value>
      <webElementGuid>970d9892-6329-428a-9ee8-137c641d8c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/mat-form-field/div/div/div/textarea</value>
      <webElementGuid>801a03e6-4291-4b67-8042-fd0f1e988ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'item_description' and @name = 'item_description']</value>
      <webElementGuid>5777bd70-4b32-41e8-91e7-a2997e694936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
