<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buat Invoice Baru</name>
   <tag></tag>
   <elementGuidId>0936e0e6-191e-408e-b480-aa73313e305e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#digpayin-step1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='digpayin-step1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c278262-253e-4a75-bea0-f03eb187aac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>digpayin-step1</value>
      <webElementGuid>d17e5300-3754-4d60-83b9-00cba932e9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paper-button blue-button ng-tns-c747-23</value>
      <webElementGuid>7ea50a26-f622-4432-a836-7edbd513dfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Buat Invoice Baru </value>
      <webElementGuid>f9e322a3-3000-4743-b937-f8f715262620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digpayin-step1&quot;)</value>
      <webElementGuid>922cf684-c6a4-42f5-903f-985887891b1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='digpayin-step1']</value>
      <webElementGuid>d8f2308f-45d2-4ee4-a98f-dbb5cb152098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div/div[4]/div/button</value>
      <webElementGuid>ef6b1444-89ab-4f6d-bfc3-2a206ff6ba17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import &amp; Download'])[1]/following::button[1]</value>
      <webElementGuid>ee72a56f-8fd7-4ee2-9310-bc45f744730f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Penjualan'])[3]/following::button[2]</value>
      <webElementGuid>82d2c252-1bf8-470b-9abc-ac6ebe1f11fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice No.'])[1]/preceding::button[1]</value>
      <webElementGuid>7b8987e7-95c2-4b96-8d46-2a9c61b4582f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelanggan'])[1]/preceding::button[1]</value>
      <webElementGuid>47b36ae1-78a5-44ae-9f54-0c8eb20e5631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buat Invoice Baru']/parent::*</value>
      <webElementGuid>739eae6e-0857-4a80-b85d-993657b8157a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>320297bc-8f6d-48e1-9cb0-a6bcdb408d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'digpayin-step1' and (text() = ' Buat Invoice Baru ' or . = ' Buat Invoice Baru ')]</value>
      <webElementGuid>0b09b698-825f-477f-a714-f58b1a93b3d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
